let jours = [
    { "numero": 1, "titre": "Urgence écologique", "texte": "Changement climatique, fonte des glaces, montée des eaux, extinction des espèces, déplacements forcées des populations, risques sanitaires, injustices économiques et sociales à court et à long terme. De l\'urgence écologique émanent des problèmes multiples et conséquents, souvent entremêlés. Or, face à l\'urgence écologique nous devons et pouvons agir. S\'il n\'est pas envisageable de sombrer dans le catastrophisme qui annihilerait la possibilité d\'agir, il ne s\'agit pas non plus d\'espérer un retour idéalisé à la nature ni même de pointer du doigt la responsabilité individuelle plus que celle d\'un système de production et de développement profondément injuste, qui se fonde sur l\'exploitation du vivant sans limite. Aussi, la lutte écologiste ne peut-être qu\'anticapitaliste et sociale.", "ouvert": false},
    { "numero": 2, "titre": "L\'écologie sociale", "texte": "text jour x", "ouvert": false},
    { "numero": 3, "titre": "", "texte": "Comme nous l\'avons dit hier, la lutte écologiste ne peut-être qu\'anticapitaliste et sociale. Aujourd\'hui, intéressons-nous de plus près à l\'écologie sociale. Théorisée par le militant et essayiste libertaire Murrray Bookchin, l\'écologie sociale met en rapport problèmes écologiques et problèmes sociaux. En effet, les différents types de dominations exercées au sein des sociétés fondées sur la hiérarchie (les hommes sur les femmes, les riches sur les pauvres, les vieux sur les jeunes etc.) se retrouvent dans la manière dont nous appréhendons notre environnement. C\'est pourquoi, penser la lutte écologiste, c\'est toujours penser les intrications sociales et politiques qui mettent à mal nos rapports les uns avec les autres. La lutte écologiste appelle le dépassement de nos sociétés de classe, capitalistes, hiérarchiques et injustes. ", "ouvert": false},
    { "numero": 4, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 5, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 6, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 7, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 8, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 9, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 10, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 11, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 12, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 13, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 14, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 15, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 16, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 17, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 18, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 19, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 20, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 21, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 22, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 23, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 24, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 25, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 26, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 27, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 28, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 29, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 30, "titre": "", "texte": "text jour x", "ouvert": false},
    { "numero": 31, "titre": "", "texte": "text jour x", "ouvert": false}
];
